version: "3.8"
services:
  database:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=schedulerx"
      - "POSTGRES_USER=hani"
      - "POSTGRES_PASSWORD=${DB_SECRET}"