spring:
  main:
    banner-mode: off
  datasource:
    username: ${DB_ID}
    password: ${DB_SECRET}
    url: jdbc:postgresql://localhost:5432/schedulerx
  security:
    jwt:
      secret-key: verysecretkeyohsosecretdamnhowlongisthispleasedontusethisinproduction
    oauth2:
      client:
        registration:
          github:
            client-id: ${GIT_ID}
            client-secret: ${GIT_SECRET}
            scope: read:public_repo
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
